---
name: Sync repo files
on:
  schedule:
    - cron: '44 17 * * *'
jobs:
  fork_check:
    name: check for fork
    runs-on: ubuntu-latest
    outputs:
      check_fork: ${{ steps.check_fork.outputs.check_fork }}
    steps:
      - uses: actions/checkout@v3
      - id: check_fork
        run: |
          FORK=$(gh repo view $(git config --get remote.origin.url) --json isFork --jq .isFork)
          echo "check_fork=$FORK" >> $GITHUB_OUTPUT
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  repo_sync:
    runs-on: ubuntu-latest
    needs: [fork_check]
    if: ${{ !needs.fork_check.outputs.check_fork }}
    container:
      image: quay.io/prometheus/golang-builder
    steps:
      - uses: actions/checkout@v3
      - run: ./scripts/sync_repo_files.sh
        env:
          GITHUB_TOKEN: ${{ secrets.PROMBOT_GITHUB_TOKEN }}
